[package]
name = "chain-watch"
version = "0.1.0"
authors = ["Enzo Cioppettini <ecioppettini@atixlabs.com>"]
edition = "2018"

[dependencies]
prost = "0.7"

[dependencies.tonic]
version = "0.4"
default-features = false
features = ["codegen", "prost"]

[build-dependencies.tonic-build]
version = "0.4"
default-features = false
features = ["prost"]

[features]
default = ["tonic/transport", "tonic-build/transport"]